### ISSUE TITLE
data → meervoud

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/datawijs#2]
Het is beetje vervelend, maar het woord "data" wordt in het Nederlands enkel in  het meervoud gebruikt (tenzij verwezen wordt naar het "star trek"-personage). "Open Data" mag gerust in het Nederlands: dan verwijs je naar het concept.

Op de homepage is dus wel correct: "Open Data _zijn_ data die ...".

Een handige hack: verander het woord data door dataset of datasets

**Comment by PieterJanPauwels** [comment]
Solved, aangepast in alle filmpjes en interactieve lagen.
